version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=project_localed_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Test1234=
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myNetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d project_localed_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/project_localed_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Test1234=
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - myNetwork
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  myNetwork:
    driver: bridge
