spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_localed_db
    username: postgres
    password: Test1234=
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev
server:
  port: 8080
